# Site settings
title: Gameplay Programmer
email: jasanth97@gmail.com
description: > # keep this and put description below
  Programmer and Designer
url: "https://jharrington-porfolio.netlify.app/" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/jason-harrington-dev/"
github_username: JHarringtonDev
twitter_username: JHarringtonDev
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
